pip install asn1crypto        
pip install azure-devops      
pip install certifi           
pip install cffi              
pip install chardet           
pip install colorama          
pip install cryptography      
pip install httplib2          
pip install idna              
pip install isodate           
pip install msrest            
pip install oauthlib          
::pip install pycparser         
pip install pyDes             
pip install PyOpenGL          
pip install pyparsing         
pip install PyQt5             
pip install PyQt5-sip         
::pip install pyserial          
::pip install pywin32           
pip install requests          
pip install requests-oauthlib 
pip install setuptools        
pip install six               
pip install Testharness==200       
pip install urllib3           
